env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules:
  import/extensions:
    - "error"
    - "ignorePackages"
    - 
      js: "never"
      mjs: "never"
      jsx: "never"
      ts: "never"
      tsx: "never"
